### ISSUE TITLE
underlay shown above content on load, in Mac Safari and Mobile Safari

### ISSUE THREAD

**Issue by kenjitayama** [motss/paper-swipe#1]
I took a video of Mobile Safari.
https://dl.dropboxusercontent.com/u/379843/paper-swipe_ios.m4v
iPhone 6 / iOS 9.2.1

paper-swipe is cool, and easy to use, and I really want to use paper-swipe in my iOS/Android app!

**Comment by motss** [comment]
@kenjitayama The issue has been confirmed. Working on a fix for Safari Mobile.

**Comment by kenjitayama** [comment]
@motss Thanks for checking!

**Comment by motss** [comment]
@kenjitayama Luckily you're here. Please took a look at the fixed version if this patch solves the issue on your device.

[https://motss.github.io/paper-swipe/components/paper-swipe/demo/](https://motss.github.io/paper-swipe/components/paper-swipe/demo/)

![fixed-paper-swipe-on-safari-mobile](https://cloud.githubusercontent.com/assets/10607759/12702659/d476a8ca-c869-11e5-8aba-e32bf6a03600.jpg)

**Comment by kenjitayama** [comment]
@motss 
Works perfect on Mobile Safari and Mac Safari. Awesome!
Looks like it was a pretty big fix. Thanks so much!

**Comment by motss** [comment]
@kenjitayama Thanks for confirmation. :smiley:
